export const clinicalFieldLabels: Record<string, string> = {
  "antibioticos": "Antibióticos",
  "analgesicos": "Analgésicos",
  "anestesicos": "Anestésicos",
  "alimentos": "Alimentos",
  "especificar": "Especificar otras alergias",
  "madre": "Madre (Padecimientos)",
  "padre": "Padre (Padecimientos)",
  "hermanos": "Hermanos (Padecimientos)",
  "hijos": "Hijos (Padecimientos)",
  "esposo": "Esposo(a) (Padecimientos)",
  "tios": "Tíos (Padecimientos)",
  "abuelos": "Abuelos (Padecimientos)",
  "frecuencia_cepillado": "Frecuencia de Cepillado",
  "grupo_sanguineo": "Grupo Sanguíneo",
  "auxiliares_higiene": "Auxiliares de higiene registrados",
  "auxiliares_otros": "Otros auxiliares (especificar)",
  "cartilla-vacunacion": "¿Cuenta con cartilla de vacunación?",
  "esquema-vacunacion": "¿Esquema completo?",
  "come_entre_comidas": "¿Come entre comidas?",
  "adic_tabaco": "Tabaco",
  "adic_alcohol": "Alcohol",
  "ets": "ETS",
  "degenerativas": "Degenerativas",
  "neoplasicas": "Neoplásicas",
  "congenitas": "Congénitas",
  "otras": "Otras",
  "apertura_mm": "Apertura (mm)",
  "lateralidad": "Lateralidad",
  "ruidos": "Ruidos",
  "chasquidos": "Chasquidos",
  "crepitacion": "Crepitación",
  "dificultad_abrir_boca": "Dificultad al abrir",
  "dolor_mov_lateralidad": "Dolor en lateralidad",
  "fatiga_dolor_muscular": "Fatiga/Dolor muscular",
  "disminucion_apertura": "Disminución de apertura",
  "desviacion_apertura_cierre": "Desviación apertura/cierre",
  "cabeza_exostosis": "Cabeza: Exostosis",
  "cabeza_endostosis": "Cabeza: Endostosis",
  "cara_asimetria_transversal": "Cara: Asimetría Transversal",
  "cara_asimetria_longitudinal": "Cara: Asimetría Longitudinal",
  "cuello_cadena_ganglionar_palpable": "Cuello: Cadena Ganglionar Palpable",
  "craneo_tipo": "Tipo de cráneo",
  "perfil": "Perfil",
  "piel": "Piel",
  "musculos": "Músculos",
  "otros": "Otros",
  "ocupacion": "Ocupación",
  "escolaridad": "Escolaridad",
  "estado_civil": "Estado Civil",
  "telefono": "Teléfono (Adicional)",
  "fecha_ult_consulta_medica": "Última consulta médica",
  "motivo_ult_consulta_medica": "Motivo de última consulta médica",
  "fecha_ult_consulta_odontologica": "Última consulta odontológica",
  "motivo_ult_consulta_odontologica": "Motivo de última consulta odontológica",
  "ha_sido_hospitalizado": "¿Ha sido hospitalizado en los últimos 5 años?",
  "fecha": "Fecha (Aprox.)",
  "motivo": "Motivo",
  "peso_kg": "Peso (kg)",
  "talla_m": "Talla (m)",
  "frecuencia_cardiaca": "Frec. Cardiaca (lpm)",
  "frecuencia_respiratoria": "Frec. Respiratoria (rpm)",
  "tension_arterial_sistolica": "T.A. Sistólica (mmHg)",
  "tension_arterial_diastolica": "T.A. Diastólica (mmHg)",
  "temperatura_c": "Temperatura (°C)",
  "paciente_niega_procedimientos": "Paciente niega procedimientos",
  "auxiliares_cuales": "Auxiliares de higiene",
  "cartilla_vacunacion": "Cuenta con cartilla de vacunación",
  "esquema_vacunacion_completo": "Esquema de vacunación completo",
  "labio_estado": "Labios (estado)",
  "labio_nota": "Labios (observaciones)",
  "comisuras_estado": "Comisuras (estado)",
  "comisuras_nota": "Comisuras (observaciones)",
  "carrillos_estado": "Carrillos (estado)",
  "carrillos_nota": "Carrillos (observaciones)",
  "fondo_de_saco_estado": "Fondo de saco (estado)",
  "fondo_de_saco_nota": "Fondo de saco (observaciones)",
  "frenillos_estado": "Frenillos (estado)",
  "frenillos_nota": "Frenillos (observaciones)",
  "paladar_estado": "Paladar (estado)",
  "paladar_nota": "Paladar (observaciones)",
  "lengua_estado": "Lengua (estado)",
  "lengua_nota": "Lengua (observaciones)",
  "piso_boca_estado": "Piso de boca (estado)",
  "piso_boca_nota": "Piso de boca (observaciones)",
  "dientes_estado": "Dientes (estado)",
  "dientes_nota": "Dientes (observaciones)",
  "encia_estado": "Encía (estado)",
  "encia_nota": "Encía (observaciones)"
};
