import type { PermissionDefinition } from "../types/permission.types";

export const permissionCatalog: PermissionDefinition[] = [
  { key: "dashboard.view", module: "dashboard", description: "Ver dashboard" },
  { key: "patients.view", module: "patients", description: "Ver pacientes" },
  { key: "patients.create", module: "patients", description: "Crear pacientes" },
  { key: "patients.update", module: "patients", description: "Actualizar pacientes" },
  { key: "patients.delete", module: "patients", description: "Eliminar pacientes" },
  { key: "patients.clinicalHistory.view", module: "patients", description: "Ver historia clinica" },
  { key: "patients.clinicalHistory.update", module: "patients", description: "Actualizar historia clinica" },
  { key: "patients.odontogram.view", module: "patients", description: "Ver odontograma" },
  { key: "patients.odontogram.update", module: "patients", description: "Actualizar odontograma" },
  { key: "services.view", module: "services", description: "Ver servicios" },
  { key: "services.create", module: "services", description: "Crear servicios" },
  { key: "quotations.view", module: "quotations", description: "Ver cotizaciones" },
  { key: "quotations.create", module: "quotations", description: "Crear cotizaciones" },
  { key: "quotations.pdf.generate", module: "quotations", description: "Generar PDF de cotizacion" },
  { key: "agenda.view", module: "agenda", description: "Ver agenda" },
  { key: "agenda.appointments.create", module: "agenda", description: "Crear citas" },
  { key: "agenda.appointments.update", module: "agenda", description: "Actualizar citas" },
  { key: "agenda.appointments.cancel", module: "agenda", description: "Cancelar citas" },
  { key: "inventory.view", module: "inventory", description: "Ver inventario" },
  { key: "inventory.stock.adjust", module: "inventory", description: "Ajustar stock" },
  { key: "sales.view", module: "sales", description: "Ver ventas" },
  { key: "sales.create", module: "sales", description: "Crear ventas" },
  { key: "sales.cashShift.open", module: "sales", description: "Abrir corte de caja" },
  { key: "sales.cashShift.close", module: "sales", description: "Cerrar corte de caja" },
  { key: "roles.view", module: "roles", description: "Ver roles" },
  { key: "roles.create", module: "roles", description: "Crear roles" },
  { key: "roles.update", module: "roles", description: "Actualizar roles" },
  { key: "roles.assign", module: "roles", description: "Asignar roles" },
  { key: "audit.view", module: "audit", description: "Ver bitacora" },
  { key: "security.sessions.view", module: "security", description: "Ver sesiones" },
  { key: "security.sessions.revoke", module: "security", description: "Revocar sesiones" },
  { key: "settings.view", module: "settings", description: "Ver configuracion" },
  { key: "settings.update", module: "settings", description: "Actualizar configuracion" },
];

export const permissionKeys = permissionCatalog.map((permission) => permission.key);
