import type { PermissionDefinition, PermissionKey } from "../types/permission.types";

export const permissionCatalog: PermissionDefinition[] = [
  // Dashboard
  {
    key: "dashboard.view",
    module: "dashboard",
    group: "Dashboard",
    label: "Ver dashboard",
    description: "Permite ver el resumen operativo del consultorio.",
    level: "read",
  },

  // Pacientes
  {
    key: "patients.view",
    module: "patients",
    group: "Pacientes",
    label: "Ver pacientes",
    description: "Permite ver la lista de pacientes y sus datos generales.",
    level: "read",
  },
  {
    key: "patients.create",
    module: "patients",
    group: "Pacientes",
    label: "Crear pacientes",
    description: "Permite registrar nuevos pacientes.",
    level: "write",
  },
  {
    key: "patients.update",
    module: "patients",
    group: "Pacientes",
    label: "Editar pacientes",
    description: "Permite modificar datos generales de pacientes.",
    level: "write",
  },
  {
    key: "patients.delete",
    module: "patients",
    group: "Pacientes",
    label: "Eliminar pacientes",
    description: "Permite eliminar pacientes del sistema.",
    level: "admin",
    isDangerous: true,
  },
  {
    key: "patients.record.view",
    module: "patients",
    group: "Ficha del paciente",
    label: "Ver ficha del paciente",
    description: "Permite abrir la ficha y consultar sus datos generales.",
    level: "read",
  },
  {
    key: "patients.procedures.view",
    module: "patients",
    group: "Historial de procedimientos",
    label: "Ver historial de procedimientos",
    description: "Permite consultar procedimientos realizados.",
    level: "read",
  },
  {
    key: "patients.procedures.create",
    module: "patients",
    group: "Historial de procedimientos",
    label: "Crear procedimientos",
    description: "Permite registrar procedimientos.",
    level: "write",
  },
  {
    key: "patients.procedures.update",
    module: "patients",
    group: "Historial de procedimientos",
    label: "Editar procedimientos",
    description: "Permite modificar procedimientos registrados.",
    level: "write",
  },
  {
    key: "patients.procedures.delete",
    module: "patients",
    group: "Historial de procedimientos",
    label: "Eliminar procedimientos",
    description: "Permite eliminar procedimientos registrados.",
    level: "write",
    isDangerous: true,
  },
  {
    key: "patients.payments.view",
    module: "patients",
    group: "Pagos del paciente",
    label: "Ver pagos del paciente",
    description: "Permite consultar pagos y cuentas por cobrar del paciente.",
    level: "read",
  },
  {
    key: "patients.quotations.view",
    module: "patients",
    group: "Cotizaciones del paciente",
    label: "Ver cotizaciones del paciente",
    description: "Permite consultar cotizaciones desde la ficha.",
    level: "read",
  },
  {
    key: "patients.clinicalHistory.view",
    module: "patients",
    group: "Historial clínico",
    label: "Ver historial clínico",
    description: "Permite ver el historial clínico del paciente.",
    level: "read",
  },
  {
    key: "patients.clinicalHistory.update",
    module: "patients",
    group: "Historial clínico",
    label: "Editar historial clínico",
    description: "Permite agregar o modificar entradas del historial clínico.",
    level: "write",
  },
  {
    key: "patients.odontogram.view",
    module: "patients",
    group: "Odontograma",
    label: "Ver odontograma",
    description: "Permite consultar el odontograma del paciente.",
    level: "read",
  },
  {
    key: "patients.odontogram.update",
    module: "patients",
    group: "Odontograma",
    label: "Editar odontograma",
    description: "Permite modificar estados dentales en el odontograma.",
    level: "write",
  },
  {
    key: "patients.attachments.view",
    module: "patients",
    group: "Adjuntos",
    label: "Ver adjuntos",
    description: "Permite ver documentos, imágenes o archivos del paciente.",
    level: "read",
  },
  {
    key: "patients.attachments.upload",
    module: "patients",
    group: "Adjuntos",
    label: "Subir adjuntos",
    description: "Permite subir documentos, imágenes o archivos al expediente del paciente.",
    level: "write",
  },
  {
    key: "patients.attachments.delete",
    module: "patients",
    group: "Adjuntos",
    label: "Eliminar adjuntos",
    description: "Permite eliminar archivos adjuntos del expediente del paciente.",
    level: "admin",
    isDangerous: true,
  },

  // Servicios
  {
    key: "services.view",
    module: "services",
    group: "Servicios individuales",
    label: "Ver servicios",
    description: "Permite ver el catálogo de servicios dentales.",
    level: "read",
  },
  {
    key: "services.create",
    module: "services",
    group: "Servicios individuales",
    label: "Crear servicios",
    description: "Permite agregar nuevos servicios dentales.",
    level: "write",
  },
  {
    key: "services.update",
    module: "services",
    group: "Servicios individuales",
    label: "Editar servicios",
    description: "Permite modificar servicios, precios o categorías.",
    level: "write",
  },
  {
    key: "services.delete",
    module: "services",
    group: "Servicios individuales",
    label: "Eliminar servicios",
    description: "Permite eliminar servicios del catálogo.",
    level: "admin",
    isDangerous: true,
  },

  // Paquetes
  {
    key: "packages.view",
    module: "packages",
    group: "Paquetes",
    label: "Ver paquetes",
    description: "Permite ver paquetes o promociones.",
    level: "read",
  },
  {
    key: "packages.create",
    module: "packages",
    group: "Paquetes",
    label: "Crear paquetes",
    description: "Permite crear paquetes o promociones.",
    level: "write",
  },
  {
    key: "packages.update",
    module: "packages",
    group: "Paquetes",
    label: "Editar paquetes",
    description: "Permite modificar paquetes o promociones.",
    level: "write",
  },
  {
    key: "packages.delete",
    module: "packages",
    group: "Paquetes",
    label: "Eliminar paquetes",
    description: "Permite eliminar paquetes o promociones.",
    level: "admin",
    isDangerous: true,
  },

  // Cotizaciones
  {
    key: "quotations.view",
    module: "quotations",
    group: "Cotizaciones",
    label: "Ver cotizaciones",
    description: "Permite ver cotizaciones existentes.",
    level: "read",
  },
  {
    key: "quotations.create",
    module: "quotations",
    group: "Cotizaciones",
    label: "Crear cotizaciones",
    description: "Permite crear nuevas cotizaciones.",
    level: "write",
  },
  {
    key: "quotations.update",
    module: "quotations",
    group: "Cotizaciones",
    label: "Editar cotizaciones",
    description: "Permite modificar cotizaciones existentes.",
    level: "write",
  },
  {
    key: "quotations.delete",
    module: "quotations",
    group: "Cotizaciones",
    label: "Eliminar cotizaciones",
    description: "Permite eliminar cotizaciones.",
    level: "admin",
    isDangerous: true,
  },
  {
    key: "quotations.pdf.generate",
    module: "quotations",
    group: "Cotizaciones",
    label: "Generar PDF",
    description: "Permite generar PDF de cotizaciones.",
    level: "read",
  },

  // Agenda
  {
    key: "agenda.view",
    module: "agenda",
    group: "Agenda general",
    label: "Ver agenda",
    description: "Permite acceder al módulo de agenda.",
    level: "read",
  },
  {
    key: "agenda.doctors.view",
    module: "agenda",
    group: "Doctores",
    label: "Ver doctores",
    description: "Permite consultar la sección de doctores.",
    level: "read",
  },
  {
    key: "agenda.assistants.view",
    module: "agenda",
    group: "Asistentes",
    label: "Ver asistentes",
    description: "Permite consultar la sección de asistentes.",
    level: "read",
  },
  {
    key: "agenda.availability.view",
    module: "agenda",
    group: "Bloqueos / disponibilidad",
    label: "Ver disponibilidad",
    description: "Permite consultar horarios y bloqueos.",
    level: "read",
  },
  {
    key: "agenda.doctors.viewAll",
    module: "agenda",
    group: "Doctores",
    label: "Ver agenda de todos los doctores",
    description: "Permite ver la disponibilidad y citas de todos los doctores.",
    level: "read",
  },
  {
    key: "agenda.doctors.viewOwn",
    module: "agenda",
    group: "Doctores",
    label: "Ver agenda propia",
    description: "Permite que un doctor vea únicamente su propia agenda.",
    level: "read",
  },
  {
    key: "agenda.doctors.manage",
    module: "agenda",
    group: "Doctores",
    label: "Gestionar doctores",
    description: "Permite configurar doctores, colores, especialidades, horarios y disponibilidad.",
    level: "manage",
  },
  {
    key: "agenda.assistants.manage",
    module: "agenda",
    group: "Asistentes",
    label: "Gestionar asistentes",
    description: "Permite configurar asistentes, turnos, horarios y permisos operativos.",
    level: "manage",
  },
  {
    key: "agenda.appointments.create",
    module: "agenda",
    group: "Agenda general",
    label: "Crear citas",
    description: "Permite crear citas programadas o espontáneas.",
    level: "write",
  },
  {
    key: "agenda.appointments.update",
    module: "agenda",
    group: "Agenda general",
    label: "Editar citas",
    description: "Permite cambiar fecha, hora, doctor, duración o categoría visual de una cita.",
    level: "write",
  },
  {
    key: "agenda.appointments.cancel",
    module: "agenda",
    group: "Agenda general",
    label: "Cancelar citas",
    description: "Permite cancelar citas existentes.",
    level: "write",
    isDangerous: true,
  },
  {
    key: "agenda.blocks.create",
    module: "agenda",
    group: "Bloqueos / disponibilidad",
    label: "Crear bloqueos de horario",
    description: "Permite bloquear horas o rangos de horario en la agenda.",
    level: "write",
  },
  {
    key: "agenda.blocks.delete",
    module: "agenda",
    group: "Bloqueos / disponibilidad",
    label: "Eliminar bloqueos de horario",
    description: "Permite liberar horarios previamente bloqueados.",
    level: "write",
    isDangerous: true,
  },
  {
    key: "agenda.changes.acknowledge",
    module: "agenda",
    group: "Agenda - Cambios",
    label: "Confirmar cambios recibidos",
    description: "Permite confirmar que el doctor vio o recibió un cambio de agenda.",
    level: "write",
  },
  {
    key: "agenda.notifications.view",
    module: "agenda",
    group: "Agenda - Notificaciones",
    label: "Ver notificaciones de agenda",
    description: "Permite ver notificaciones por cambios o asignaciones de citas.",
    level: "read",
  },

  // Inventario
  {
    key: "inventory.view",
    module: "inventory",
    group: "Inventario",
    label: "Ver inventario",
    description: "Permite consultar productos, existencias, categorías, entradas y movimientos. No permite modificar stock.",
    level: "read",
  },
  {
    key: "inventory.create",
    module: "inventory",
    group: "Inventario",
    label: "Crear productos",
    description: "Permite registrar productos nuevos.",
    level: "write",
  },
  {
    key: "inventory.update",
    module: "inventory",
    group: "Inventario",
    label: "Editar productos",
    description: "Permite modificar productos, categorías, unidades o estado.",
    level: "write",
  },
  {
    key: "inventory.delete",
    module: "inventory",
    group: "Inventario",
    label: "Eliminar productos",
    description: "Permite eliminar productos del inventario.",
    level: "admin",
    isDangerous: true,
  },
  {
    key: "inventory.categories.manage",
    module: "inventory",
    group: "Inventario",
    label: "Gestionar categorías",
    description: "Permite crear o modificar categorías de inventario.",
    level: "manage",
  },
  {
    key: "inventory.usage.create",
    module: "inventory",
    group: "Inventario - Uso",
    label: "Registrar uso de producto",
    description: "Permite registrar quién tomó o usó producto, para qué y cuándo.",
    level: "write",
  },
  {
    key: "inventory.stock.adjust",
    module: "inventory",
    group: "Inventario - Stock",
    label: "Ajustar stock y reabastecer",
    description: "Permite registrar entradas y ajustes manuales de existencias. Requiere ver inventario.",
    level: "manage",
    isDangerous: true,
  },
  {
    key: "inventory.costs.view",
    module: "inventory",
    group: "Inventario - Costos",
    label: "Ver costos",
    description: "Permite ver costos internos de productos.",
    level: "read",
  },
  {
    key: "inventory.purchaseList.manage",
    module: "inventory",
    group: "Inventario - Compras",
    label: "Registrar reabastecimientos",
    description: "Permite registrar compras, aumentar stock y guardar sus movimientos de entrada. Requiere ver inventario; no permite ajustes ni editar productos.",
    level: "manage",
  },

  // Ventas / caja
  {
    key: "sales.view",
    module: "sales",
    group: "Ventas",
    label: "Ver ventas",
    description: "Permite consultar ventas e ingresos.",
    level: "read",
  },
  {
    key: "sales.create",
    module: "sales",
    group: "Ventas",
    label: "Crear ventas",
    description: "Permite registrar ventas de productos, tratamientos o servicios.",
    level: "write",
  },
  {
    key: "sales.cancel",
    module: "sales",
    group: "Ventas",
    label: "Cancelar ventas",
    description: "Permite cancelar ventas registradas.",
    level: "admin",
    isDangerous: true,
  },
  {
    key: "sales.payments.manage",
    module: "sales",
    group: "Ventas - Pagos",
    label: "Gestionar pagos y abonos",
    description: "Permite registrar pagos, métodos de pago y abonos.",
    level: "write",
  },
  {
    key: "sales.cashShift.open",
    module: "sales",
    group: "Caja",
    label: "Abrir caja",
    description: "Permite abrir caja o iniciar turno con caja inicial.",
    level: "write",
  },
  {
    key: "sales.cashShift.close",
    module: "sales",
    group: "Caja",
    label: "Cerrar caja",
    description: "Permite cerrar caja, hacer corte y entrega de turno.",
    level: "manage",
  },
  {
    key: "sales.cashCuts.history.view",
    module: "sales",
    group: "Caja",
    label: "Ver cortes anteriores",
    description: "Permite consultar cortes de caja históricos.",
    level: "read",
  },
  {
    key: "sales.expenses.create",
    module: "sales",
    group: "Gastos",
    label: "Registrar gastos",
    description: "Permite registrar gastos del turno o consultorio.",
    level: "write",
  },
  {
    key: "sales.reports.view",
    module: "sales",
    group: "Reportes de ventas",
    label: "Ver reportes de ventas",
    description: "Permite ver reportes financieros de ventas, gastos y caja.",
    level: "read",
  },

  // Bitácora
  {
    key: "audit.view",
    module: "audit",
    group: "Bitácora",
    label: "Ver bitácora",
    description: "Permite consultar el historial de acciones del sistema.",
    level: "read",
  },

  // Seguridad
  {
    key: "security.sessions.view",
    module: "security",
    group: "Seguridad",
    label: "Ver sesiones",
    description: "Permite consultar sesiones activas de usuarios.",
    level: "read",
  },
  {
    key: "security.sessions.revoke",
    module: "security",
    group: "Seguridad",
    label: "Revocar sesiones",
    description: "Permite cerrar sesiones activas de otros usuarios.",
    level: "admin",
    isDangerous: true,
  },

  // Usuarios
  {
    key: "users.view",
    module: "users",
    group: "Usuarios",
    label: "Ver usuarios",
    description: "Permite consultar usuarios del sistema.",
    level: "read",
  },
  {
    key: "users.create",
    module: "users",
    group: "Usuarios",
    label: "Crear usuarios",
    description: "Permite registrar usuarios internos del consultorio.",
    level: "admin",
  },
  {
    key: "users.update",
    module: "users",
    group: "Usuarios",
    label: "Editar usuarios",
    description: "Permite modificar información o estado de usuarios.",
    level: "admin",
  },
  {
    key: "users.block",
    module: "users",
    group: "Usuarios",
    label: "Bloquear usuarios",
    description: "Permite bloquear o desactivar usuarios.",
    level: "admin",
    isDangerous: true,
  },
  {
    key: "users.delete",
    module: "users",
    group: "Usuarios",
    label: "Eliminar usuarios",
    description: "Permite eliminar usuarios del sistema.",
    level: "admin",
    isDangerous: true,
  },

  // Roles
  {
    key: "roles.view",
    module: "roles",
    group: "Roles",
    label: "Ver roles",
    description: "Permite consultar roles y permisos configurados.",
    level: "read",
  },
  {
    key: "roles.create",
    module: "roles",
    group: "Roles",
    label: "Crear roles",
    description: "Permite crear roles personalizados.",
    level: "admin",
  },
  {
    key: "roles.update",
    module: "roles",
    group: "Roles",
    label: "Editar roles",
    description: "Permite modificar permisos de roles existentes.",
    level: "admin",
    isDangerous: true,
  },
  {
    key: "roles.delete",
    module: "roles",
    group: "Roles",
    label: "Eliminar roles",
    description: "Permite eliminar roles personalizados.",
    level: "admin",
    isDangerous: true,
  },
  {
    key: "roles.assign",
    module: "roles",
    group: "Roles",
    label: "Asignar roles",
    description: "Permite asignar roles a usuarios.",
    level: "admin",
    isDangerous: true,
  },

  // Reportes generales
  {
    key: "reports.view",
    module: "reports",
    group: "Reportes",
    label: "Ver reportes generales",
    description: "Permite consultar reportes generales del consultorio.",
    level: "read",
  },
  {
    key: "reports.export",
    module: "reports",
    group: "Reportes",
    label: "Exportar reportes",
    description: "Permite exportar reportes del sistema.",
    level: "read",
  },

  // Configuración
  {
    key: "settings.view",
    module: "settings",
    group: "Configuración",
    label: "Ver configuración",
    description: "Permite consultar configuración general del sistema.",
    level: "read",
  },
  {
    key: "settings.update",
    module: "settings",
    group: "Configuración",
    label: "Editar configuración",
    description: "Permite modificar configuración general del sistema.",
    level: "admin",
    isDangerous: true,
  },
];

export const permissionKeys: PermissionKey[] = permissionCatalog.map(
  (permission) => permission.key,
);

export const hiddenRolePermissionKeys: PermissionKey[] = [
  "patients.attachments.view",
  "patients.attachments.upload",
  "patients.attachments.delete",
  "sales.reports.view",
  "reports.view",
  "reports.export",
];

const hiddenRolePermissionKeySet = new Set<PermissionKey>(hiddenRolePermissionKeys);

export const rolePermissionCatalog = permissionCatalog.filter(
  (permission) => !hiddenRolePermissionKeySet.has(permission.key),
);

export const rolePermissionKeys: PermissionKey[] = rolePermissionCatalog.map(
  (permission) => permission.key,
);

export const permissionCatalogByKey = permissionCatalog.reduce(
  (acc, permission) => {
    acc[permission.key] = permission;
    return acc;
  },
  {} as Record<PermissionKey, PermissionDefinition>,
);

export const permissionsByModule = permissionCatalog.reduce(
  (acc, permission) => {
    if (!acc[permission.module]) {
      acc[permission.module] = [];
    }

    acc[permission.module].push(permission);
    return acc;
  },
  {} as Record<string, PermissionDefinition[]>,
);
